### ISSUE TITLE
Results are not generated for Scenarios with Examples table if running Cucumber with '-x'/'--expand' parameter

### ISSUE THREAD

**Issue by kirillzh** [allure-framework/allure-cucumber#31]
`-x, --expand                     Expand Scenario Outline Tables in output.`

**Comment by 9ikhan** [comment]
Running 
```
cucumber -r features -x --format AllureCucumber::Formatter
```
Gives the following output:
``` sh
Starting case_or_suite Amazon Search with labels {:severity=>:normal}
Stopping case_or_suite Amazon Search
```

I'll debug it but, it can you explain your use case? Because `Expand Scenario Outline Tables in output.` is possible in allure report.

**Comment by kirillzh** [comment]
@9ikhan, the use case is pretty much what title says (I updated it). Allure results are not generated for Scenario Outlines if `-x` parameter is passed. Thanks!

**Comment by bayandin** [comment]
Just want to confirm, it doesn't work with the latest release (v0.5.6). Now it fails with en error:
```
$ cucumber -x --format AllureCucumber::Formatter features/addition.feature
undefined method `[]=' for nil:NilClass (NoMethodError)
/Volumes/Second/repos/allure-cucumber/lib/allure-cucumber/formatter.rb:82:in `after_scenario'
/Volumes/Second/repos/allure-cucumber/lib/allure-cucumber/formatter.rb:87:in `after_feature_element'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.4.0/lib/cucumber/formatter/ignore_missing_messages.rb:10:in `method_missing'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:622:in `after'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:309:in `after'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:123:in `after'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:52:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `each'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:40:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.4.0/lib/cucumber/filters/quit.rb:17:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:19:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core/compiler.rb:23:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core/gherkin/parser.rb:35:in `done'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:29:in `parse'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:18:in `compile'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:67:in `run!'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/Users/bayandin/.rvm/gems/ruby-2.1.5/bin/cucumber:22:in `load'
/Users/bayandin/.rvm/gems/ruby-2.1.5/bin/cucumber:22:in `<main>'
/Users/bayandin/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/bayandin/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by learnseleniumtesting** [comment]
I have bunch of feature files and Scenario outline: is everywhere. It generate only xml where feature file as on Scenario not Scenario outline;
Ruby 2.3.3/Cucumber 2

**Comment by cperezprieto** [comment]
Any update on this? I'm facing the same issue

**Comment by andrcuns** [comment]
This is solved in new adaptor implementation v2.13.0
